//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CANStream.Forms {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Frm_CANConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frm_CANConfiguration() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CANStream.Forms.Frm_CANConfiguration", typeof(Frm_CANConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit0_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit0.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit1_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit1.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit2_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit2.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit3_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit3.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit4_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit4.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit5_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit5.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit6_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit6.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Boolean semblable à True.
        /// </summary>
        internal static bool Bit7_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Bit7.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=167,Y=17}.
        /// </summary>
        internal static System.Drawing.Point Context_TV_Messages_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Context_TV_Messages.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=56}.
        /// </summary>
        internal static System.Drawing.Point Dlg_SelectColor_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Dlg_SelectColor.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer Img_TV_Messages_ImageStream {
            get {
                object obj = ResourceManager.GetObject("Img_TV_Messages.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point Img_TV_Messages_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Img_TV_Messages.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=444,Y=17}.
        /// </summary>
        internal static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=584,Y=17}.
        /// </summary>
        internal static System.Drawing.Point saveFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=339,Y=17}.
        /// </summary>
        internal static System.Drawing.Point toolStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Point semblable à {X=720,Y=17}.
        /// </summary>
        internal static System.Drawing.Point ToolTip_Commands_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("ToolTip_Commands.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
